version: "0.1"

services:
    backend:
        build: ./backend
        image: dataiku-chatbot-backend
        ports:
            - "8000:8000"
        networks:
            - dataiku-net
        depends_on:
            - postgres

    frontend:
        build: ./frontend
        image: dataiku-chatbot-frontend
        ports:
            - "5173:5173"
        networks:
            - dataiku-net

    postgres:
        image: postgres:16
        restart: always
        volumes:
            - ./postgresql-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: postgres
            POSTGRES_EXTENSIONS: vector
        networks:
            - dataiku-net
networks:
    dataiku-net:
        driver: bridge
